# Generated by Django 5.2.6 on 2025-10-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('duracion_semanas', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('numero_estudiantes', models.IntegerField()),
            ],
        ),
    ]
